### ISSUE TITLE
warning on installation

### ISSUE THREAD

**Issue by cmillion** [nkarasiak/MuseoToolBox#27]
When installing with `python3 -m pip install museotoolbox --user`, _pip_ throws the following:

> WARNING: The scripts f2py, f2py3 and f2py3.7 are installed in '/home/[user]/.local/bin' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

This might be a non-issue for functionality. I don't know.

openjournals/joss-reviews#1978

**Comment by nkarasiak** [comment]
hi @cmillion,
Here is an answer : 
https://stackoverflow.com/questions/58051467/fixing-path-for-python-libraries-using-bash
If you want to install with f2py support (which is a scipy dependency), just remove the` --user` and add `sudo` before `python3` command.

**Comment by cmillion** [comment]
I understand. Thank you.
