### ISSUE TITLE
"osgeo" dependency missing

### ISSUE THREAD

**Issue by cmillion** [nkarasiak/MuseoToolBox#28]
Starting from a fresh install of _miniconda_ with this package installed.

`from museotoolbox.ai import SuperLearner`

fails with

> ModuleNotFoundError: No module named 'osgeo'

Which isn't in the requirements.txt.

openjournals/joss-reviews#1978

**Comment by cmillion** [comment]
"osgeo" is in GDAL, so you this is fixed by installing _gdal_

**Comment by nkarasiak** [comment]
> Starting from a fresh install of _miniconda_ with this package installed.
> 
> `from museotoolbox.ai import SuperLearner`
> 
> fails with
> 
> > ModuleNotFoundError: No module named 'osgeo'
> 
> Which isn't in the requirements.txt.
> 
> [openjournals/joss-reviews#1978](https://github.com/openjournals/joss-reviews/issues/1978)

How did you install Museo ToolBox?
As it is not possible to install gdal via pip,  I created a conda feedstock to ease the installation process.
Here it is : https://github.com/conda-forge/museotoolbox-feedstock

I'll update the readme file to detail the gdal part. 
Thanks for the feedback.

**Comment by cmillion** [comment]
In installed with `python3 -m pip install museotoolbox --user` per documentation.

**Comment by nkarasiak** [comment]
Ok thanks, can you install via conda and tell me if it's okay for you ?
`conda install -c conda-forge museotoolbox`
just uninstall gdal and museotoolbox before. 
Sorry for the inconvenience.
